/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRANSAKSI;

import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Rahmatina
 */
public class Transaksi extends javax.swing.JFrame {
    public Statement stt;
    public Connection con;
    private TableColumn column;
    private final DefaultTableModel tabel;
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String temp_transaksi="";
    int jmlbelii, total, kem, bayar, harga;
    
    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        String[] judul={"ID TRANSAKSI", "TGL TRANSAKSI", "ID PELANGGAN", "NAMA PELANGGAN", "ID KARYAWAN", "NAMA KARYAWAN", "KODE OBAT", "NAMA OBAT", "HARGA OBAT", "JML BELI", "TOTAL", "BAYAR", "KEMBALIAN"};
        tabel = new DefaultTableModel(judul,0);
        jTable1.setModel(tabel);
        tampilkan_data();
        tampil_pelanggan();
        tampil_karyawan();
        tampil_obat();
        clear();
        penomoran_otomatis();
        aturKolom();
    }
    
    private void tampilkan_data() {
        try {
            int data = jTable1.getRowCount();
            for(int i=0;i<data;i++){
                tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tb_transaksi ORDER BY id_transaksi");            
            while(re.next()){                
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5),re.getString(6),re.getString(7),re.getString(8),re.getString(9),re.getString(10),re.getString(11),re.getString(12),re.getString(13)};
                tabel.addRow(tabel_master);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }
    
    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kembali = new javax.swing.JTextField();
        idtrans = new javax.swing.JTextField();
        nmpelanggan = new javax.swing.JTextField();
        nmkaryawan = new javax.swing.JTextField();
        nmobat = new javax.swing.JTextField();
        hargaa = new javax.swing.JTextField();
        jmlbeli = new javax.swing.JTextField();
        bayarr = new javax.swing.JTextField();
        cbobat = new javax.swing.JComboBox<>();
        cbkaryawan = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbpelanggan = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        totall = new javax.swing.JTextField();
        tgl = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSAKSI PENJUALAN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 33)); // NOI18N
        jLabel1.setText("APOTEK RF");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 270, 60));

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel2.setText("ID Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 27));

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel3.setText("Tanggal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 110, 27));

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel4.setText("ID Pelanggan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, 27));

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel5.setText("Nama Pelanggan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, 27));

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel6.setText("Kode Obat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 110, 27));

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel7.setText("Nama Obat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 110, 27));

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel8.setText("ID Karyawan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, 27));

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel9.setText("Nama Karyawan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 120, 27));

        jLabel10.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel10.setText("Harga");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, 27));

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel11.setText("Jumlah Beli");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 120, 27));

        jLabel12.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel12.setText("Bayar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 120, 27));

        jLabel13.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel13.setText("Kembalian");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 120, 27));

        jTable1.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 980, 140));

        kembali.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 210, 30));

        idtrans.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        idtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtransActionPerformed(evt);
            }
        });
        getContentPane().add(idtrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, 30));

        nmpelanggan.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        nmpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(nmpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 210, 30));

        nmkaryawan.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        nmkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmkaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(nmkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 210, 30));

        nmobat.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        nmobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmobatActionPerformed(evt);
            }
        });
        getContentPane().add(nmobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 210, 30));

        hargaa.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        hargaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaaActionPerformed(evt);
            }
        });
        getContentPane().add(hargaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 210, 30));

        jmlbeli.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        jmlbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlbeliActionPerformed(evt);
            }
        });
        getContentPane().add(jmlbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 210, 30));

        bayarr.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        bayarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarrActionPerformed(evt);
            }
        });
        getContentPane().add(bayarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 210, 30));

        cbobat.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        cbobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbobatActionPerformed(evt);
            }
        });
        getContentPane().add(cbobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 210, 30));

        cbkaryawan.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        cbkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(cbkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 210, 30));

        jButton2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, -1, -1));

        jButton3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 100, -1));

        jButton4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, -1, -1));

        cbpelanggan.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        cbpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(cbpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 210, 30));

        jLabel14.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel14.setText("Total");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 120, 27));

        totall.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        totall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totallActionPerformed(evt);
            }
        });
        getContentPane().add(totall, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 210, 30));

        tgl.setDateFormatString("dd MMMM  yyyy");
        tgl.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 210, 30));

        jButton5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton5.setText("CLOSE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, 100, -1));

        jButton6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton6.setText("CLEAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 100, -1));

        jLabel15.setFont(new java.awt.Font("Engravers MT", 1, 33)); // NOI18N
        jLabel15.setText("TRANSAKSI PENJUALAN");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 570, 60));

        jPanel1.setBackground(new java.awt.Color(255, 175, 175));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        setSize(new java.awt.Dimension(1032, 760));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void idtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtransActionPerformed

    private void nmpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmpelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmpelangganActionPerformed

    private void nmkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmkaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmkaryawanActionPerformed

    private void nmobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmobatActionPerformed

    private void hargaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaaActionPerformed

    private void jmlbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlbeliActionPerformed
        // TODO add your handling code here:
        jmlbelii = Integer.parseInt(jmlbeli.getText());
        harga = Integer.parseInt(hargaa.getText());

        
        total= jmlbelii * harga;
        totall.setText (total +"");

        
    }//GEN-LAST:event_jmlbeliActionPerformed

    private void bayarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarrActionPerformed
        // TODO add your handling code here:
        total = Integer.parseInt(totall.getText());
        bayar = Integer.parseInt(bayarr.getText());

        
        kem= bayar - total;
        kembali.setText (kem +"");
    }//GEN-LAST:event_bayarrActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          // TODO add your handling code here:
String id_transaksi = idtrans.getText();
String tgl_transaksi = String.valueOf(kal.format(tgl.getDate()));;
String id_pelanggan = (String) cbpelanggan.getSelectedItem();
String nama_pelanggan = nmpelanggan.getText();
String id_karyawan = (String) cbkaryawan.getSelectedItem();
String nama_karyawan = nmkaryawan.getText();
String id_obat = (String) cbobat.getSelectedItem();
String nama_obat = nmobat.getText();
String harga = hargaa.getText();
String jml_beli = jmlbeli.getText();
String total = totall.getText();
String bayar = bayarr.getText();
String kembalian = kembali.getText();

{
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/apotek_rahmatina", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="insert into tb_transaksi values('"+id_transaksi+"','"+tgl_transaksi+"','"+id_pelanggan+"','"+nama_pelanggan+"','"+id_karyawan+"','"+nama_karyawan+"','"+id_obat+"','"+nama_obat+"','"+harga+"','"+jml_beli+"','"+total+"','"+bayar+"','"+kembalian+"')";
int executeUpdate = statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "DATA TRANSAKSI BERHASIL DISIMPAN","Insert Data",JOptionPane.INFORMATION_MESSAGE);
idtrans.setText("");
tgl.setDate(null);
cbpelanggan.setSelectedItem("");
nmpelanggan.setText("");
cbkaryawan.setSelectedItem("");
nmkaryawan.setText("");
cbobat.setSelectedItem("");
nmobat.setText("");
hargaa.setText("");
jmlbeli.setText("");
totall.setText("");
bayarr.setText("");
kembali.setText("");

koneksi.close();
}
catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
finally {
tampilkan_data();
penomoran_otomatis();
}
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
String id_transaksi = idtrans.getText();
String tgl_transaksi = String.valueOf(kal.format(tgl.getDate()));;
String id_pelanggan = (String) cbpelanggan.getSelectedItem();
String nama_pelanggan = nmpelanggan.getText();
String id_karyawan = (String) cbkaryawan.getSelectedItem();
String nama_karyawan = nmkaryawan.getText();
String id_obat = (String) cbobat.getSelectedItem();
String nama_obat = nmobat.getText();
String harga = hargaa.getText();
String jml_beli = jmlbeli.getText();
String total = totall.getText();
String bayar = bayarr.getText();
String kembalian = kembali.getText();
try {
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/apotek_rahmatina", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="UPDATE tb_transaksi SET id_transaksi='"+id_transaksi+"',tgl_transaksi='"+tgl_transaksi+"',id_pelanggan='"+id_pelanggan+"',nama_pelanggan='"+nama_pelanggan+"',id_karyawan='"+id_karyawan+"',nama_karayawan='"+nama_karyawan+"',kode_obat='"+id_obat+"',nama_obat='"+nama_obat+"',harga='"+harga+"',jml_beli='"+jml_beli+"',total='"+total+"',bayar='"+bayar+"',kembalian='"+kembalian+"' WHERE id_transaksi ='"+id_transaksi+"'";
statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "DATA TRANSAKSI BERHASIL DIEDIT","Insert Data",JOptionPane.INFORMATION_MESSAGE);
koneksi.close();
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}finally{
tampilkan_data();
penomoran_otomatis();
}
tgl.setDate(null);
cbpelanggan.setSelectedItem("");
nmpelanggan.setText("");
cbkaryawan.setSelectedItem("");
nmkaryawan.setText("");
cbobat.setSelectedItem("");
nmobat.setText("");
hargaa.setText("");
jmlbeli.setText("");
totall.setText("");
bayarr.setText("");
kembali.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpelangganActionPerformed
          // TODO add your handling code here:
nmpelanggan.setText(null);
String pp = (String) cbpelanggan.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/apotek_rahmatina", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM tb_pelanggan WHERE id_pelanggan like '"+pp+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{

nmpelanggan.setText(rs.getString(2));

}

statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    
    }//GEN-LAST:event_cbpelangganActionPerformed

    private void cbkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkaryawanActionPerformed
         // TODO add your handling code here:
nmkaryawan.setText(null);
String pp = (String) cbkaryawan.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/apotek_rahmatina", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM tb_karyawan WHERE id_karyawan like '"+pp+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{

nmkaryawan.setText(rs.getString(2));

}

statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    
    }//GEN-LAST:event_cbkaryawanActionPerformed

    private void cbobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbobatActionPerformed
         // TODO add your handling code here:
nmobat.setText(null);
String pp = (String) cbobat.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/apotek_rahmatina", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="SELECT * FROM tb_obat WHERE kd_obat like '"+pp+"'";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{

nmobat.setText(rs.getString(2));
hargaa.setText(rs.getString(5));

}

statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    
    }//GEN-LAST:event_cbobatActionPerformed

    private void totallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totallActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(idtrans.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "PILIH DATA TERLEBIH DAHULU");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(this,"YAKIN HAPUS DATA TRANSAKSI?","Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    java.sql.Connection koneksi = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
                    koneksi.createStatement().executeUpdate("DELETE FROM tb_transaksi where id_transaksi='"+idtrans.getText()+"'");
                    JOptionPane.showMessageDialog(this, "DATA TRANSAKSI BERHASIL DIHAPUS");
                    tampilkan_data();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "DATA TRANSAKSI GAGAL DIHAPUS");
                }
                
            }
            tgl.setDate(null);
            cbpelanggan.setSelectedItem("");
            nmpelanggan.setText("");
            cbkaryawan.setSelectedItem("");
            nmkaryawan.setText("");
            cbobat.setSelectedItem("");
            nmobat.setText("");
            hargaa.setText("");
            jmlbeli.setText("");
            totall.setText("");
            bayarr.setText("");
            kembali.setText("");
            penomoran_otomatis();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
idtrans.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
 java.util.Date tgl_lhr=null;
        try{
            tgl_lhr = new SimpleDateFormat("yyyy-MM-dd").parse(tabel.getValueAt(jTable1.getSelectedRow(), 1).toString());            
        }catch(ParseException ex){
            System.out.println(ex);
        }
        tgl.setDate(tgl_lhr);
cbpelanggan.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
nmpelanggan.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
cbkaryawan.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
nmkaryawan.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
cbobat.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
nmobat.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
hargaa.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
jmlbeli.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
totall.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
bayarr.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString());
kembali.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 12).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         // TODO add your handling code here:
idtrans.setText("");
tgl.setDate(null);
cbpelanggan.setSelectedItem("");
nmpelanggan.setText("");
cbkaryawan.setSelectedItem("");
nmkaryawan.setText("");
cbobat.setSelectedItem("");
nmobat.setText("");
hargaa.setText("");
jmlbeli.setText("");
totall.setText("");
bayarr.setText("");
kembali.setText("");
penomoran_otomatis();
    }//GEN-LAST:event_jButton6ActionPerformed

private void clear() {
    idtrans.setText("");
tgl.setDate(null);
cbpelanggan.setSelectedItem("");
nmpelanggan.setText("");
cbkaryawan.setSelectedItem("");
nmkaryawan.setText("");
cbobat.setSelectedItem("");
nmobat.setText("");
hargaa.setText("");
jmlbeli.setText("");
totall.setText("");
bayarr.setText("");
kembali.setText("");
    
}
private void tampil_pelanggan() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tb_pelanggan ORDER BY id_pelanggan ASC");
            while(re.next()){
                cbpelanggan.addItem(re.getString("id_pelanggan"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Pelanggan !");
        }
    }

private void tampil_karyawan() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tb_karyawan ORDER BY id_karyawan ASC");
            while(re.next()){
                cbkaryawan.addItem(re.getString("id_karyawan"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Karyawan !");
        }
    }

private void tampil_obat() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tb_obat ORDER BY kd_obat ASC");
            while(re.next()){
                cbobat.addItem(re.getString("kd_obat"));
                nmobat.setText(re.getString("nama_obat"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Obat !");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }
    
    private void penomoran_otomatis() {
        int no_transaksi=0;
        String temp_transaksi="";
        try {
            koneksi();
            String sql = "select id_transaksi from tb_transaksi order by id_transaksi desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_transaksi = res.getString(1);                
                String nomor_blkg = temp_transaksi.substring(2,4);
                no_transaksi=Integer.parseInt(nomor_blkg);
            }
                        
            no_transaksi++;
            String nilai=String.valueOf(no_transaksi);                      
            if(nilai.length()==1){
                idtrans.setText("T00"+no_transaksi);
            }else
            if(nilai.length()==2){
                idtrans.setText("T0"+no_transaksi);
            }else
            if(nilai.length()==3){
                idtrans.setText("T"+no_transaksi);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }
    
    private void aturKolom() {
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = jTable1.getColumnModel().getColumn(0);
        column.setPreferredWidth(70);        
        column = jTable1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(100); 
        column = jTable1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(70);
        column = jTable1.getColumnModel().getColumn(3); 
        column.setPreferredWidth(80);
        column = jTable1.getColumnModel().getColumn(4); 
        column.setPreferredWidth(70);
        column = jTable1.getColumnModel().getColumn(5); 
        column.setPreferredWidth(80);
        column = jTable1.getColumnModel().getColumn(6); 
        column.setPreferredWidth(70);
        column = jTable1.getColumnModel().getColumn(7); 
        column.setPreferredWidth(82);
        column = jTable1.getColumnModel().getColumn(8); 
        column.setPreferredWidth(70);
        column = jTable1.getColumnModel().getColumn(9); 
        column.setPreferredWidth(70);
        column = jTable1.getColumnModel().getColumn(10); 
        column.setPreferredWidth(70);
        column = jTable1.getColumnModel().getColumn(11); 
        column.setPreferredWidth(70);
        column = jTable1.getColumnModel().getColumn(12); 
        column.setPreferredWidth(70);
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayarr;
    private javax.swing.JComboBox<String> cbkaryawan;
    private javax.swing.JComboBox<String> cbobat;
    private javax.swing.JComboBox<String> cbpelanggan;
    private javax.swing.JTextField hargaa;
    private javax.swing.JTextField idtrans;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jmlbeli;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField nmkaryawan;
    private javax.swing.JTextField nmobat;
    private javax.swing.JTextField nmpelanggan;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextField totall;
    // End of variables declaration//GEN-END:variables
}
