/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MASTER;

import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Rahmatina
 */
public class Data_Karyawan extends javax.swing.JFrame {
public Statement stt;
private final DefaultTableModel tabel;
    public Connection con;
    private TableColumn column;
    String temp_karyawan="";
    /**
     * Creates new form Data_Karyawan
     */
    public Data_Karyawan() {
        initComponents();
        String[] judul={"ID KARYAWAN","NAMA KARYAWAN","JENIS KELAMIN","ALAMAT","STATUS","NO TELEPON"};
        tabel = new DefaultTableModel(judul,0);
        jTable2.setModel(tabel);
        tampilkan_data();
        penomoran_otomatis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ealamat = new javax.swing.JTextField();
        enama = new javax.swing.JTextField();
        eid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbjenis = new javax.swing.JComboBox<>();
        cbstatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        eno = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA KARYAWAN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 153, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 33)); // NOI18N
        jLabel1.setText("APOTEK RF");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 270, 55));

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel2.setText("ID Karyawan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 121, 28));

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel3.setText("Nama Karyawan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 121, 28));

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 121, 28));

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 121, 28));

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel6.setText("Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 121, 28));

        ealamat.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        getContentPane().add(ealamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 190, 30));

        enama.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        getContentPane().add(enama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 190, 28));

        eid.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidActionPerformed(evt);
            }
        });
        getContentPane().add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 190, 28));

        jButton2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 98, 33));

        jButton3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 98, 33));

        jButton4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 98, 33));

        cbjenis.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        getContentPane().add(cbjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 190, 28));

        cbstatus.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tetap", "Kontrak" }));
        getContentPane().add(cbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 190, 29));

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel7.setText("No Telepon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 121, 28));

        eno.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        getContentPane().add(eno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 190, 28));

        jTable2.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama Karyawan", "Jenis Kelamin", "Alamat", "Status", "No. Telepon"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 660, 150));

        jButton5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton5.setText("CLOSE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 100, 30));

        jLabel8.setFont(new java.awt.Font("Engravers MT", 1, 33)); // NOI18N
        jLabel8.setText("DATA KARYAWAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 430, 55));

        jPanel2.setBackground(new java.awt.Color(255, 175, 175));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        setSize(new java.awt.Dimension(716, 743));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
String id_karyawan = eid.getText();
String nama_karyawan = enama.getText();
String jenis_kelamin = (String) cbjenis.getSelectedItem();
String alamat = ealamat.getText();
String status = (String) cbstatus.getSelectedItem();
String no_telepon = eno.getText();

{
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/apotek_rahmatina", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="insert into tb_karyawan values('"+id_karyawan+"','"+nama_karyawan+"','"+jenis_kelamin+"','"+alamat+"','"+status+"','"+no_telepon+"')";
int executeUpdate = statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "DATA KARYAWAN BERHASIL DISIMPAN","Insert Data",JOptionPane.INFORMATION_MESSAGE);
enama.setText("");
cbjenis.setSelectedItem("");
ealamat.setText("");
cbstatus.setSelectedItem("");
eno.setText("");

koneksi.close();
}
catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
finally {
tampilkan_data();
penomoran_otomatis();
}
    }             
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_eidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         // TODO add your handling code here:
String id_karyawan = eid.getText();
String nama_karyawan = enama.getText();
String jenis_kelamin = (String) cbjenis.getSelectedItem();
String alamat = ealamat.getText();
String status = (String) cbstatus.getSelectedItem();
String no_telepon = eno.getText();
try {
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/apotek_rahmatina", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="UPDATE tb_karyawan SET id_karyawan='"+id_karyawan+"',nama_karyawan='"+nama_karyawan+"',jenis_kelamin='"+jenis_kelamin+"',alamat='"+alamat+"',status='"+status+"',no_telepon='"+no_telepon+"' WHERE id_karyawan ='"+id_karyawan+"'";
statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "DATA KARYAWAN BERHASIL DIEDIT","Insert Data",JOptionPane.INFORMATION_MESSAGE);
koneksi.close();
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}finally{
tampilkan_data();
enama.setText("");
cbjenis.setSelectedItem("");
ealamat.setText("");
cbstatus.setSelectedItem("");
eno.setText("");
penomoran_otomatis();
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
         // TODO add your handling code here:
        eid.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        enama.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        cbjenis.setSelectedItem(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
        ealamat.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        cbstatus.setSelectedItem(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        eno.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString());
       
        temp_karyawan = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(eid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "PILIH DATA TERLEBIH DAHULU");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(this,"YAKIN HAPUS DATA KARYAWAN?","Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    java.sql.Connection koneksi = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
                    koneksi.createStatement().executeUpdate("DELETE FROM tb_karyawan where id_karyawan='"+eid.getText()+"'");
                    JOptionPane.showMessageDialog(this, "DATA KARYAWAN BERHASIL DIHAPUS");
                    tampilkan_data();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "DATA KARYAWAN GAGAL DIHAPUS");
                }
                
            }
        eid.setText("");
        enama.setText("");
        cbjenis.setSelectedItem("");
        ealamat.setText("");
        cbstatus.setSelectedItem("");
        eno.setText("");
        penomoran_otomatis();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();;
    }//GEN-LAST:event_jButton5ActionPerformed

    
    private void tampilkan_data() {
        try {
            int data = jTable2.getRowCount();
            for(int i=0;i<data;i++){
                tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tb_karyawan ORDER BY id_karyawan");            
            while(re.next()){                
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5),re.getString(6)};
                tabel.addRow(tabel_master);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Karyawan().setVisible(true);
            }
        });
    }
    
     private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
     
     private void penomoran_otomatis() {
        int no_karyawan=0;
        String temp_karyawan="";
        try {
            koneksi();
            String sql = "select id_karyawan from tb_karyawan order by id_karyawan desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_karyawan = res.getString(1);                
                String nomor_blkg = temp_karyawan.substring(2,4);
                no_karyawan=Integer.parseInt(nomor_blkg);
            }
                        
            no_karyawan++;
            String nilai=String.valueOf(no_karyawan);                      
            if(nilai.length()==1){
                eid.setText("K00"+no_karyawan);
            }else
            if(nilai.length()==2){
                eid.setText("K0"+no_karyawan);
            }else
            if(nilai.length()==3){
                eid.setText("K"+no_karyawan);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JTextField ealamat;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField enama;
    private javax.swing.JTextField eno;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
