/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MASTER;

import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Rahmatina
 */
public class Data_Pelanggan extends javax.swing.JFrame {
    public Statement stt;
    public Connection con;
    private TableColumn column;
    private final DefaultTableModel tabel;
    String temp_pelanggan="";
    

    /**
     * Creates new form Data_Pelanggan
     */
    public Data_Pelanggan() {
        initComponents();
        String[] judul={"ID PELANGGAN","NAMA PELANGGAN","ALAMAT","JENIS KELAMIN","NO TELEPON"};
        tabel = new DefaultTableModel(judul,0);
        jTable1.setModel(tabel);
        
        tampilkan_data();
        penomoran_otomatis();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        enama = new javax.swing.JTextField();
        ealamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        eno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cbjenis = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA PELANGGAN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama Pelanggan", "Alamat", "Jenis Kelamin", "No Telepon"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 720, 160));

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel6.setText("No Telepon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 121, 28));

        eid.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        getContentPane().add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 190, 28));

        enama.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        getContentPane().add(enama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 190, 28));

        ealamat.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        getContentPane().add(ealamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 190, 28));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 33)); // NOI18N
        jLabel1.setText("APOTEK RF");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 270, 55));

        eno.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        getContentPane().add(eno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 190, 28));

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel2.setText("ID Pelanggan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 121, 28));

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel3.setText("Nama Pelanggan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 121, 28));

        jButton2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton2.setText("SIMPAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 98, 33));

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 121, 28));

        jButton3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 98, 33));

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 17)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 121, 28));

        jButton4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 98, 33));

        cbjenis.setFont(new java.awt.Font("Calisto MT", 0, 15)); // NOI18N
        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        getContentPane().add(cbjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 190, 28));

        jButton5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton5.setText("CLOSE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 100, 30));

        jLabel7.setFont(new java.awt.Font("Engravers MT", 1, 33)); // NOI18N
        jLabel7.setText("DATA PELANGGAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 440, 55));

        jPanel1.setBackground(new java.awt.Color(255, 175, 175));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 610));

        setSize(new java.awt.Dimension(773, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        eid.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        enama.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        ealamat.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        cbjenis.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        eno.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
       
        temp_pelanggan = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // TODO add your handling code here:
String id_pelanggan = eid.getText();
String nama_pelanggan = enama.getText();
String alamat = ealamat.getText();
String jenis = (String) cbjenis.getSelectedItem();
String no_telepon = eno.getText();

{
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/apotek_rahmatina", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="insert into tb_pelanggan values('"+id_pelanggan+"','"+nama_pelanggan+"','"+alamat+"','"+jenis+"','"+no_telepon+"')";
int executeUpdate = statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "DATA PELANGGAN BERHASIL DISIMPAN","Insert Data",JOptionPane.INFORMATION_MESSAGE);
enama.setText("");
ealamat.setText("");
cbjenis.setSelectedItem("");
eno.setText("");

koneksi.close();
}
catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
finally {
tampilkan_data();
penomoran_otomatis();
}
    }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
String id_pelanggan = eid.getText();
String nama_pelanggan = enama.getText();
String alamat = ealamat.getText();
String jenis = (String) cbjenis.getSelectedItem();
String no_telepon = eno.getText();
try {
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/apotek_rahmatina", "root", "");
Statement statement = (Statement) koneksi.createStatement();
String sql="UPDATE tb_pelanggan SET id_pelanggan='"+id_pelanggan+"',nama_pelanggan='"+nama_pelanggan+"',alamat='"+alamat+"',jenis_kelamin='"+jenis+"',no_telepon='"+no_telepon+"' WHERE id_pelanggan ='"+id_pelanggan+"'";
statement.executeUpdate(sql);
statement.close();
JOptionPane.showMessageDialog(null, "DATA PELANGGAN BERHASIL DIEDIT","Insert Data",JOptionPane.INFORMATION_MESSAGE);
koneksi.close();
} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}finally{
tampilkan_data();
penomoran_otomatis();
}
enama.setText("");
ealamat.setText("");
cbjenis.setSelectedItem("");
eno.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(eid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "PILIH DATA TERLEBIH DAHULU");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(this,"YAKIN HAPUS DATA PELANGGAN?","Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    java.sql.Connection koneksi = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
                    koneksi.createStatement().executeUpdate("DELETE FROM tb_pelanggan where id_pelanggan='"+eid.getText()+"'");
                    JOptionPane.showMessageDialog(this, "DATA PELANGGAN BERHASIL DIHAPUS");
                    tampilkan_data();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "DATA PELANGGAN GAGAL DIHAPUS");
                    
                }
                
            }
            enama.setText("");
            ealamat.setText("");
            cbjenis.setSelectedItem("");
            eno.setText("");
            penomoran_otomatis();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tampilkan_data() {
        try {
            int data = jTable1.getRowCount();
            for(int i=0;i<data;i++){
                tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM tb_pelanggan ORDER BY id_pelanggan");            
            while(re.next()){                
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5)};
                tabel.addRow(tabel_master);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }
    
    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_rahmatina","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
    
    private void penomoran_otomatis() {
        int no_pelanggan=0;
        String temp_pelanggan="";
        try {
            koneksi();
            String sql = "select id_pelanggan from tb_pelanggan order by id_pelanggan desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_pelanggan = res.getString(1);                
                String nomor_blkg = temp_pelanggan.substring(2,4);
                no_pelanggan=Integer.parseInt(nomor_blkg);
            }
                        
            no_pelanggan++;
            String nilai=String.valueOf(no_pelanggan);                      
            if(nilai.length()==1){
                eid.setText("P00"+no_pelanggan);
            }else
            if(nilai.length()==2){
                eid.setText("P0"+no_pelanggan);
            }else
            if(nilai.length()==3){
                eid.setText("P"+no_pelanggan);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Pelanggan().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JTextField ealamat;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField enama;
    private javax.swing.JTextField eno;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
